"""adiciona email ao cliente

Revision ID: 13c23a725ef2
Revises: 54b40f179d88
Create Date: 2026-06-16 18:33:24.665209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c23a725ef2'
down_revision: Union[str, Sequence[str], None] = '54b40f179d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'email')
    # ### end Alembic commands ###
