"""cria tabela auditoria

Revision ID: 42b62705192a
Revises: 13c23a725ef2
Create Date: 2026-06-16 18:38:45.061368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b62705192a'
down_revision: Union[str, Sequence[str], None] = '13c23a725ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=True),
    sa.Column('operacao', sa.String(length=20), nullable=True),
    sa.Column('data', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria')
    # ### end Alembic commands ###
