"""estrutura inicial

Revision ID: 54b40f179d88
Revises: 
Create Date: 2026-06-16 18:30:23.603427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b40f179d88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id_pagamento', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id_hospedagem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_pagamento')
    )
    op.create_index(op.f('ix_pagamentos_id_pagamento'), 'pagamentos', ['id_pagamento'], unique=False)
    op.create_table('suites',
    sa.Column('id_suite', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('valor_hora', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_suite'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_suites_id_suite'), 'suites', ['id_suite'], unique=False)
    op.create_table('hospedagens',
    sa.Column('id_hospedagem', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.String(length=20), nullable=False),
    sa.Column('data_saida', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_suite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_suite'], ['suites.id_suite'], ),
    sa.PrimaryKeyConstraint('id_hospedagem')
    )
    op.create_index(op.f('ix_hospedagens_id_hospedagem'), 'hospedagens', ['id_hospedagem'], unique=False)
    op.create_table('consumos',
    sa.Column('id_consumo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_hospedagem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospedagem'], ['hospedagens.id_hospedagem'], ),
    sa.PrimaryKeyConstraint('id_consumo')
    )
    op.create_index(op.f('ix_consumos_id_consumo'), 'consumos', ['id_consumo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumos_id_consumo'), table_name='consumos')
    op.drop_table('consumos')
    op.drop_index(op.f('ix_hospedagens_id_hospedagem'), table_name='hospedagens')
    op.drop_table('hospedagens')
    op.drop_index(op.f('ix_suites_id_suite'), table_name='suites')
    op.drop_table('suites')
    op.drop_index(op.f('ix_pagamentos_id_pagamento'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
